# see https://symfony.com/doc/current/reference/configuration/framework.html
framework:
    secret: '%env(APP_SECRET)%'
    #csrf_protection: true
    http_method_override: false
    handle_all_throwables: true

    # Enables session support. Note that the session will ONLY be started if you read or write from it.
    # Remove or comment this section to explicitly disable session support.
    session:
        handler_id: null
        cookie_secure: auto
        cookie_samesite: lax
        storage_factory_id: session.storage.factory.native

    #esi: true
    #fragments: true
    php_errors:
        log: true

    # Scoped http clients
    http_client:
        scoped_clients:
            cdek.client:
                base_uri: '%cdek_base_url%'
                timeout: 10
                max_duration: 10
                headers:
                    Content-Type: 'application/json'
            dellin.client:
                base_uri: '%dellin_base_url%'
                timeout: 10
                max_duration: 10
                headers:
                    Content-Type: 'application/json'
            dostavista.client:
                base_uri: '%dostavista_base_url%'
                timeout: 10
                max_duration: 10
                headers:
                    Content-Type: 'application/json'
                    X-DV-Auth-Token: '%dostavista_token%'
            pvzcdek.client:
                base_uri: '%cdek_base_url%'
                headers:
                    Content-Type: 'application/json'

when@test:
    framework:
        test: true
        session:
            storage_factory_id: session.storage.factory.mock_file
